/*
 * RESTAPISDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
package com.thoughtspot.UserAndGroupCurdSample;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import com.google.gson.Gson;
import localhost.RESTAPISDKClient;
import localhost.controllers.GroupController;
import localhost.controllers.UserController;
import localhost.exceptions.ApiException;
import localhost.models.*;

/**
 * User CRUD operations.
 */
public class UserMethods extends ControllerBase {

    /**
     * Search for active users.
     *
     * @param client RESTAPISDKClient.
     * @return list of user names.
     * @throws IOException .
     * @throws ApiException .
     */
    public List<String> searchActiveUsers(RESTAPISDKClient client)
            throws IOException, ApiException {
        UserController userController = client.getUserController();

        TspublicRestV2UserSearchRequest tspublicRestV2UserSearchRequest =
                new TspublicRestV2UserSearchRequest();
        tspublicRestV2UserSearchRequest.setState(SearchUsersStateEnum.ACTIVE);

        String user = (String) userController.searchUsers(tspublicRestV2UserSearchRequest);

        Gson gson = new Gson();
        List<UserResponse> userResponse = gson.fromJson(
                user,
                new com.google.gson.reflect.TypeToken<List<UserResponse>>() {
                }.getType());

        List<String> names = userResponse.stream().map(
                name -> name.getName()).collect(Collectors.toList());

        return names;
    }

    /**
     * Create new user.
     *
     * @param client RESTAPISDKClient.
     * @param users list users.
     * @return list of user response objects.
     * @throws IOException .
     * @throws ApiException .
     */
    public List<UserResponse> createNewUser(
            RESTAPISDKClient client, List<TspublicRestV2UserCreateRequest> users)
            throws IOException, ApiException {

        List<UserResponse> result = new ArrayList<>();
        UserController userController = client.getUserController();

        for (TspublicRestV2UserCreateRequest tspublicRestV2UserCreateRequest : users) {
            result.add(userController.createUser(tspublicRestV2UserCreateRequest));
        }

        return result;
    }

    /**
     * Create new user.
     *
     * @param client RESTAPISDKClient.
     * @return list of user response objects.
     * @throws IOException .
     * @throws ApiException .
     */
    public Boolean deleteUser(
            RESTAPISDKClient client, UserNameAndID user)
            throws IOException, ApiException {

        UserController userController = client.getUserController();
        return userController.deleteUser(user.getName(), null);
    }
}
